### ISSUE TITLE
GIAC GSE was changed. etc...

### ISSUE THREAD

**Issue by R-yu-2** [PaulJerimy/SecCertRoadmapHTML#105]
1. Although GSE occupies the top of this roadmap, the system has undergone major changes.
Two types are available: GSE (GIAC Security Expert) and GSP (GIAC Security Professional).
Due to this change, the following New certifications (Applied Knowledge Certifications) required to obtain GSE or GSP have been newly established.
https://www.giac.org/get-certified/giac-portfolio-certifications/

- GIAC Experienced Cybersecurity Specialist Certification [(GX-CS)](https://www.giac.org/certifications/experienced-cyber-security-gxcs/)
- GIAC Experienced Forensics Analyst [(GX-FA)](https://www.giac.org/certifications/experienced-forensic-analyst-gxfa/)
- GIAC Experienced Intrusion Analyst Certification [(GX-IA)](https://www.giac.org/certifications/experienced-intrusion-analyst-gxia/)
- GIAC Experienced Incident Handler Certification [(GX-IH)](https://www.giac.org/certifications/experienced-incident-handler-gxih/)
- GIAC Experienced Penetration Tester [(GX-PT)](https://www.giac.org/certifications/experienced-penetration-tester-gxpt/)

2. Regarding EC-Council's CEH, a new practical exam ([CEH Practical)](https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh-practical/) has also been introduced, and those who pass both CEH and CEH Practical will be certified as [CEH Master.](https://www.eccouncil.org/train-certify/ceh-master/)
CEH Practical is like CyberLive.

3. For GIAC and CompTIA,new certifications have been established.
(Both are areas of data science, and I don't know where to list them in this roadmap, which is classified based on CISSP Domains...)
GIAC(SANS)・・GIAC Machine Learning Engineer [(GMLE)](https://www.giac.org/certifications/machine-learning-engineer-gmle/)
CompTIA・・・[Data+](https://www.comptia.org/certifications/data),[DataSys+](https://www.comptia.org/certifications/datasys)

4. The link for AppleACSP (Apple Certified Support Professional) is broken.
(I couldn't find the correct link.)

**Comment by sinecurelife** [comment]
Thank you, I have updated the GSE description and added the GSP
