### ISSUE TITLE
About certifications of ISC2.

### ISSUE THREAD

**Issue by R-yu-2** [PaulJerimy/SecCertRoadmapHTML#108]
1.CISSP-Concentrations's page was divided. The current linked page no longer exists.
ISSAP
https://www.isc2.org/certifications/issap
ISSEP
https://www.isc2.org/certifications/issep
ISSMP
https://www.isc2.org/certifications/issmp

2.HCISPP Certification to be Sunset.
https://www.isc2.org/notice/HCISPP-sunset
The final exam date is December 1, 2023.

**Comment by sinecurelife** [comment]
Thank you, I have corrected the links and removed HCISPP
