### ISSUE TITLE
About GIAC.

### ISSUE THREAD

**Issue by R-yu-2** [PaulJerimy/SecCertRoadmapHTML#111]
1.GPPA is Retired.
https://www.giac.org/retired-certifications/

2.GPYC's classify
SANS previously classified SEC573(GPYC's course) as "Specialized Penetration Testing"(current "Specialized Offensive Operations"), but now classifies it as "Cyber Defense Operations".
Along with this change, the GPYC badge's color has also changed from red to blue.

Current(2023).
https://www.sans.org/cyber-security-skills-roadmap/?msc=course-list-lp

Previous(2020).
https://web.archive.org/web/20201206191931/https://www.sans.org/cyber-security-skills-roadmap?msc=course-list-lp

**Comment by R-yu-2** [comment]
GIAC Red Team Professional (GRTP)
https://www.sans.org/cyber-security-courses/red-team-operations-adversary-emulation/

**Comment by R-yu-2** [comment]
The following certifications have disappeared as the courses have disappeared.

GIAC Enterprise Vulnerability Assessor Certification (GEVA)
https://www.giac.org/certifications/enterprise-vulnerability-assessor-geva

**Comment by R-yu-2** [comment]
GIAC Enterprise Incident Response (GEIR) 

https://www.giac.org/certifications/giac-enterprise-incident-responder-geir/

**Comment by sinecurelife** [comment]
Thank you, I have removed the retired GIAC certifications and added the new ones. I will also look for ones we might have missed from GIAC.
