### ISSUE TITLE
May want to add the SecOps Certifications in

### ISSUE THREAD

**Issue by ahnospell44** [PaulJerimy/SecCertRoadmapHTML#122]
Unfortunately, I do not see the guidelines for submitting new cert information into the chart, but: 

SecOps is a newer Cert group: https://secops.group/pentesting-exams/

![2024-04-11_16-54-42](https://github.com/PaulJerimy/SecCertRoadmapHTML/assets/7912525/ead80813-b9bb-4bf6-841d-03123922b3ca)

**Comment by sinecurelife** [comment]
Thank you for bringing these to my attention. I have added them to the roadmap.
