### ISSUE TITLE
Include new nomenclature of Fortinet certifications

### ISSUE THREAD

**Issue by peterspbr** [PaulJerimy/SecCertRoadmapHTML#125]
Fortinet certifications now have new nomenclatures, instead of "NSE" they are now called FCA, FCP, FCE...
It would be interesting to include that, or change the existing ones to the new names.

**Comment by sinecurelife** [comment]
Thank you for bringing these to my attention. I have replaced the NSE certifications with the 11 new Fortinet versions

**Comment by kur00n3k0** [comment]
Thank you!
