### ISSUE TITLE
International Pricing for Certifications

### ISSUE THREAD

**Issue by mdawsonuk** [PaulJerimy/SecCertRoadmapHTML#2]
Currently the pricing is only in US$ - perhaps adding other prices where relevant for certifications would show the certification's availability around the world and be more intuitive for international users. I can work on this over the next few weeks and submit a PR if it is a feature that's wanted?

**Comment by sinecurelife** [comment]
That would be outstanding! Yes, that feature is a bit above my knowledge level.

No rush at all as this is a continuously evolving project.

**Comment by mdawsonuk** [comment]
That would be fine. I was thinking of of a $xx/£xx/€xx format which would be clearer for users (and if any other pricing options are available I would include them too in the same format).

**Comment by sinecurelife** [comment]
Awesome thank you. Given the traffic to the chart, dollars, pounds, euros, and Indian rupees are probably the top 4.

**Comment by mdawsonuk** [comment]
@sinecurelife Have started work on international prices/price updates on [my fork](https://github.com/mdawsonuk/SecCertRoadmapHTML/tree/feature/international-pricing) - would appreciate feedback

**Comment by sinecurelife** [comment]
@mdawsonuk Thanks for the hard work! It looks good. It feels like that's going to be a lot of work.

**Comment by mdawsonuk** [comment]
@sinecurelife For sure - but it'll be worth it to give more reliable pricing to users. 

I'm interested on your take on currency conversion e.g. when a currency is only available in USD. I'm reluctant to provide any seemingly accurate conversion as that'll only be accurate at the time it was converted. An alternative could be rounding up/down to the nearest tenth and then using a tilde signifying approximation? This was noticeable with the NCSC certifications - the conversion from GBP to USD meant the price was a little out.

Also, some of the prices I'm struggling to find the original values - some just don't seem to be publicly available.

**Comment by sinecurelife** [comment]
I'm currently working on making a Python/Django version of this chart which has the ability to use logic and variables. In that version I intend to have a selector for currency (and later language) and have the code translate the prices automagically based on the current currency conversion rate.

Given the difficulties of manually gathering and entering that information on the HTML chart, perhaps we should leave the official price in the original currency on the chart. I could maybe add a currency converter just below the chart so people can convert without having to open another window.

Some certification agencies are very vague about what is required to take their exam and how much it'll cost. The most annoying ones post the cost for their special optional course and hide the price of the exam alone until you dig into the website for awhile.

**Comment by sinecurelife** [comment]
That other project will be at https://github.com/sinecurelife/SecCertRoadmap

Currently all the code is on my computer as I learn how to properly use GitHub Desktop for syncing.  I'm also not sure how to share a database properly in GitHub, but I'll figure it out eventually!

**Comment by mdawsonuk** [comment]
I'd certainly be interested in collaborating on that with you. It would certainly be much easier in terms of data addition and changes if it's stored in a database or flat-file format. 

In terms of sharing databases, the general rule of thumb is to not commit databases to Git - perhaps a collection of JSON files would work better - would allow easier collaboration, version control and readability?

**Comment by sinecurelife** [comment]
Thanks for the insight. I did the database design and created a PostgresSQL database. Now I'm wrapping my head around the python/django and how to integrate that with my website.

**Comment by tsluyter** [comment]
> I'm interested on your take on currency conversion e.g. when a currency is only available in USD. I'm reluctant to provide any seemingly accurate conversion as that'll only be accurate at the time it was converted. 

I would suggest that this chart should only display official pricing as advertised by the vendors in question. If the vendor doesn't provide a price point in EUR, GBP or INR I would not include it.
