### ISSUE TITLE
proficiency levels

### ISSUE THREAD

**Issue by mrboogiee** [PaulJerimy/SecCertRoadmapHTML#3]
Can proficiency levels be added like:

- Novice (unskilled, not knowing, new to) 
- Beginner (Learning) 
- Competent (knows adequately, qualified) 
- Proficient (practiced, skillful) 
- Expert (well practiced, having versatile knowledge) 

Currently the ordering (work your way up from the bottom) is not clear for the people that are new to the cyber security arena.

**Comment by sinecurelife** [comment]
This is a great idea that I am not sure how to address. If anyone knows a good way to denote this on the chart, please do a pull request.

**Comment by tsluyter** [comment]
I'll give it a shot at some point. The problem is that there's no clear delineation between these levels, especially when you start comparing apples to oranges. What might be "expert" level in one area could potentially be considered peanuts to people whose expertise is in another field.

**Comment by sinecurelife** [comment]
Yes I agree. There's a lot of subjectiveness in aggregating opinions about 400 certifications into a (nearly) readable chart. On the old image version I had a proficiency level based on feedback from people on social media that was relatively successful.

Here's that version for reference:
[https://pauljerimy.com/OC/Security%20Certification%20Progression%20Chart%20v6.2.png](url)

I just don't know how to add a horizontal overlay for proficiencies on top of the CSS Grid styles. My usage of vmax to scale the chart to different screen sizes is not proportional which makes adding another grid look horrible.

**Comment by sinecurelife** [comment]
Added a column for skills levels and divided by Beginner / Intermediate / Advanced. I left it purposely vague because these skill levels are subjective. This will be reflected in Release 8
