### ISSUE TITLE
Add MITRE Certifications

### ISSUE THREAD

**Issue by sinecurelife** [PaulJerimy/SecCertRoadmapHTML#45]
Review and place MITRE certifications if appropriate.

https://mitre-engenuity.org/mad/

**Comment by noraj** [comment]
- name: MITRE ATT&CK DEFENDER™ (MAD)
- link: https://mitre-engenuity.org/mad/
- price: 299 USD

**Comment by sinecurelife** [comment]
Added MAD CTI and MAD SOCA to release 8 (April 2022)
