### ISSUE TITLE
ADD GIAC Public Cloud Security (GPCS)

### ISSUE THREAD

**Issue by sinecurelife** [PaulJerimy/SecCertRoadmapHTML#47]
Research the GIAC Public Cloud Security and add to the chart if appropriate.

**Comment by noraj** [comment]
- name: GIAC Public Cloud Security (GPCS)
- link: https://www.giac.org/certifications/public-cloud-security-gpcs/
- price: 2,499 USD

**Comment by sinecurelife** [comment]
Added GPCS in release 8 (April 2022)
