### ISSUE TITLE
Dark Vortex certifications

### ISSUE THREAD

**Issue by noraj** [PaulJerimy/SecCertRoadmapHTML#51]
- [x] Malware On Steroids - https://0xdarkvortex.dev/training-programs/malware-on-steroids/ - $2000 USD
- [x] Offensive Tool Development - https://0xdarkvortex.dev/training-programs/offensive-tool-development/ - $2000 USD
- [x] Red Team & Operational Security - https://0xdarkvortex.dev/training-programs/red-team-and-operational-security/ - $2500 USD
- [x] Adversary Operations & Proactive Hunting - https://0xdarkvortex.dev/training-programs/adversary-operations-and-proactive-hunting/ - $2500 USD
- [x] Malware Incident & Log Forensics - https://0xdarkvortex.dev/training-programs/malware-incident-and-log-forensics/ - $2500 USD

**Comment by sinecurelife** [comment]
Added Dark Vortex certifications: DV MoS, DV RTOS, DV OTD, DV AOPH, and DV MILF
