### ISSUE TITLE
Add CPTS

### ISSUE THREAD

**Issue by noraj** [PaulJerimy/SecCertRoadmapHTML#76]
HTB Certified Penetration Testing Specialist (HTB CPTS)

https://academy.hackthebox.com/preview/certifications/htb-certified-penetration-testing-specialist/

**Comment by sinecurelife** [comment]
Thank you for the information. added in January 2023 release

**Comment by noraj** [comment]
HTB have 3 new certifications https://academy.hackthebox.com/preview/certifications
