### ISSUE TITLE
S-CISO correct information please

### ISSUE THREAD

**Issue by deanbushmiller** [PaulJerimy/SecCertRoadmapHTML#80]
There are no $75 exam on any section of https://www.seco-institute.org/certifications/information-security-track/
https://www.seco-institute.org/certifications-guide/
"To turn your exam certificate into a verifiable qualification that can improve your career prospects,  you need to [unlock your Practitioner certification title in the (S)ECO-System, our professional community](https://members.seco-institute.org/your-certification/unlock-your-title/). This takes only a few minutes and a small annual maintenance fee (€75, exclusive VAT)." 
--this is like the JD powers awards, where you get the cert, and can only prove you have it with  an annual maintenance fee.
further support
 "Your Certified Officer credentials will be valid for a year. To keep your Certified Officer certification title and digital badge active, you will need to re-certify every year. To re-certify, you need to pay the annual maintenance fee of €150 and report at least 40 [Continuing Professional Education (CPE) credits](https://members.seco-institute.org/your-certification/cpe-credit-registration/quick-cpe-guide/) in the (S)ECO-System.

THERE IS:
[Information Security Foundation Exam](https://www.seco-institute.org/product/information-security-foundation-exam/)
€380,00 (€380,00)

[Information Security Practitioner Exam](https://www.seco-institute.org/product/information-security-practitioner-exam/)
€450,00 (€450,00)

Neither of these belongs above the CASP or CISSP line. 
They are closed source so you cannot look at the outline without paying for a course. There are course outlines NOT exam outlines.

**Comment by sinecurelife** [comment]
Agreed. Removed "fee" and moved S-CISO down 5 rows on par with GSLC and 1 above CASP+
