### ISSUE TITLE
Webpage blocked by Safelinks

### ISSUE THREAD

**Issue by elvarb** [PaulJerimy/SecCertRoadmapHTML#89]
Microsoft Safelinks is blocking the site for being malicious.

I have not found any reason to why but upon checking the domain on mxtoolbox there I saw that the domain is on 3 blacklists, one of them being spamhaus. 
- https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3apauljerimy.com&run=toolpage

On spamhaus it is stated that the roadmap page contains malicious content, 
- https://check.spamhaus.org/listed/?searchterm=pauljerimy.com

> pauljerimy.com was listed because we have credible evidence that the webserver or CMS is compromised or infected. One of the malicious files can be found below; please be aware there can be more than one. Do not just remove this file. The site has been compromised and needs to be secured.
> 
> hXXps://pauljerimy.com/security-certification-roadmap/

Nothing on urlscan
- https://urlscan.io/result/c93fce64-5151-4424-a1a7-30726504d174/

Nothing on talos
- https://talosintelligence.com/reputation_center/lookup?search=pauljerimy.com

Nothing on forcepoint
- https://csi.forcepoint.com/Report/Index/a9fb1269-1108-4204-89ed-afc0006d3ea3

**Comment by sinecurelife** [comment]
Hey thanks for bringing this to my attention. I forgot to come back and let you know what happened.

One of my web forms was allowing someone to spam from my domain. Once I deleted the web form, the spam stopped. Hopefully Safelinks trusts me now.
