### ISSUE TITLE
Missing ISO 12700X Certifications

### ISSUE THREAD

**Issue by fkoppGAINC** [PaulJerimy/SecCertRoadmapHTML#95]
src: https://en.wikipedia.org/wiki/List_of_computer_security_certifications

**Lead Auditor**
- CIS LA | Certified ISO 27001 ISMS Lead Auditor
- ISO/IEC 27001-27002-LA | ISO 27001-27002 Lead Auditor
- ISO/IEC 27001-LA | ISO 27001:2013 ISMS Certified Lead Auditor

**Comment by sinecurelife** [comment]
Hi there, these are under the security assessment domain. They start with PECB.
