### ISSUE TITLE
The SecOps Group certifications

### ISSUE THREAD

**Issue by noraj** [PaulJerimy/SecCertRoadmapHTML#97]
https://secops.group/cyber-security-certifications/

- Essentials
  - [ ] Certified AppSec Practitioner (CAP)
  - [ ] Certified Blockchain Practitioner (CBP)
  - [ ] Certified Cloud Security Practitioner-AWS (CCSP-AWS)
  - [ ] Certified Network Security Practitioner (CNSP)
- Professional
  - [ ] Certified AppSec Pentester (CAPen)
  - [ ] Certified Network Pentester (CNPen)
  - [ ] Certified Mobile Pentester (CMPen) – Android
  - [ ] Certified Pentester (CPen)
  - [ ] Black Hat Certified Pentester (BCPen)
- eXpert
  - [ ] Certified Cloud Pentesting eXpert-AWS (CCPenX-AWS)

**Comment by sinecurelife** [comment]
Hi there, I have added the SecOps Group certifications
